/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistema.musicserver.UI;

import com.sistema.musicserver.analizadores.pista.LexerPista;
import com.sistema.musicserver.analizadores.pista.parser;
import com.sistema.musicserver.archivos.ManejadorArchivos;
import com.sistema.musicserver.errors.ErroresSingleton;
import com.sistema.musicserver.instrucciones.funciones.FunMensaje;
import com.sistema.musicserver.instrucciones.music.HiloReproductorDePista;
import com.sistema.musicserver.instrucciones.music.ManejadorPistaMusical;
import com.sistema.musicserver.instrucciones.music.PistaMusical;
import com.sistema.musicserver.pista.Lista;
import com.sistema.musicserver.pista.PistasCompiladas;
import java.io.Reader;
import java.io.StringReader;
import javax.swing.JOptionPane;

/**
 *
 * @author elvis_agui
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private final NumeroLinea numeroLineaPista;
    private parser parser;
    private LexerPista lexer;
    private ManejadorArchivos menjdorArchivos;
    private ManejadorListas majeList;
    private HiloReproductorDePista reproducctor = new HiloReproductorDePista();
    private boolean reproduciendo = false;
    private Lista listaenReproduccion = new Lista();
    private Lista listasEnModificacion = new Lista();
    private boolean yoTeDetube = false;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.majeList = new ManejadorListas();
        this.numeroLineaPista = new NumeroLinea(LenguajePistajTextArea);
        LenguajePistajScrollPane.setRowHeaderView(numeroLineaPista);
        this.majeList.mostrarListasJlist(ListaListasjList);
        this.majeList.mostrarPistasExistentes(pistasExistentesjList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelEditor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConsolaPistasjTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        LenguajePistajScrollPane = new javax.swing.JScrollPane();
        LenguajePistajTextArea = new javax.swing.JTextArea();
        compilarjButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaListasjList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pistasListaReprojList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        modificarListajButton = new javax.swing.JButton();
        eliminarListajButton = new javax.swing.JButton();
        reproducirListajButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        eliminarPistadeListajButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        modificarListajList = new javax.swing.JList<>();
        titlepistaModifjLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        pistasExistentesjList = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        agregarPistaListajButton = new javax.swing.JButton();
        crearNuevaListajButton = new javax.swing.JButton();
        nombreNuevaListajTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        CrearPistajMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidore de Reproduccion");
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        PanelEditor.setBackground(new java.awt.Color(153, 153, 255));
        PanelEditor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelEditor.setForeground(new java.awt.Color(102, 102, 255));

        ConsolaPistasjTextArea1.setEditable(false);
        ConsolaPistasjTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        ConsolaPistasjTextArea1.setColumns(20);
        ConsolaPistasjTextArea1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        ConsolaPistasjTextArea1.setForeground(new java.awt.Color(0, 102, 102));
        ConsolaPistasjTextArea1.setRows(5);
        ConsolaPistasjTextArea1.setText("Consola de Resultados o Errores");
        jScrollPane1.setViewportView(ConsolaPistasjTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1051, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        LenguajePistajTextArea.setBackground(new java.awt.Color(255, 255, 255));
        LenguajePistajTextArea.setColumns(20);
        LenguajePistajTextArea.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LenguajePistajTextArea.setForeground(new java.awt.Color(0, 0, 0));
        LenguajePistajTextArea.setRows(5);
        LenguajePistajTextArea.setText("Ingrese aqui el lenguaje de definicion de Pistas :)");
        LenguajePistajScrollPane.setViewportView(LenguajePistajTextArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LenguajePistajScrollPane)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LenguajePistajScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        compilarjButton.setText("Compilar");
        compilarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compilarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEditorLayout = new javax.swing.GroupLayout(PanelEditor);
        PanelEditor.setLayout(PanelEditorLayout);
        PanelEditorLayout.setHorizontalGroup(
            PanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelEditorLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(compilarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelEditorLayout.setVerticalGroup(
            PanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelEditorLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(compilarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Editor de Codigo", PanelEditor);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        ListaListasjList.setBackground(new java.awt.Color(255, 255, 255));
        ListaListasjList.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        ListaListasjList.setForeground(new java.awt.Color(0, 102, 51));
        jScrollPane2.setViewportView(ListaListasjList);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Listas de Reproduccion");

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setText("Areá de Reproduccion");

        jPanel7.setBackground(new java.awt.Color(102, 102, 255));

        jButton1.setText("Reproducir/Pausar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jLabel3.setText("Pista en Reproduccion");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pistasListaReprojList.setBackground(new java.awt.Color(204, 204, 255));
        pistasListaReprojList.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pistasListaReprojList.setFont(new java.awt.Font("Hack", 3, 14)); // NOI18N
        pistasListaReprojList.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(pistasListaReprojList);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Pistas de la Lista en Reproduccion");

        modificarListajButton.setText("Modificar");
        modificarListajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarListajButtonActionPerformed(evt);
            }
        });

        eliminarListajButton.setText("Eliminar");
        eliminarListajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarListajButtonActionPerformed(evt);
            }
        });

        reproducirListajButton.setText("Reproducir");
        reproducirListajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproducirListajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(modificarListajButton)
                        .addGap(34, 34, 34)
                        .addComponent(eliminarListajButton)
                        .addGap(35, 35, 35)
                        .addComponent(reproducirListajButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(modificarListajButton)
                                .addComponent(eliminarListajButton))
                            .addComponent(reproducirListajButton))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Biblioteca Musical", jPanel4);

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));
        jPanel8.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Areá de Edicion de Pistas y Listas de pistas");

        jPanel9.setBackground(new java.awt.Color(102, 102, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        eliminarPistadeListajButton.setText("Eliminar");
        eliminarPistadeListajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPistadeListajButtonActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pistas de la Lista");

        modificarListajList.setBackground(new java.awt.Color(255, 255, 255));
        modificarListajList.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        modificarListajList.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(modificarListajList);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(eliminarPistadeListajButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarPistadeListajButton)
                .addGap(20, 20, 20))
        );

        titlepistaModifjLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        titlepistaModifjLabel.setForeground(new java.awt.Color(0, 0, 0));
        titlepistaModifjLabel.setText("Pista En Edicion: -----");

        jPanel10.setBackground(new java.awt.Color(102, 102, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Pistas Existentes");

        pistasExistentesjList.setBackground(new java.awt.Color(255, 255, 255));
        pistasExistentesjList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pistasExistentesjList.setFont(new java.awt.Font("Droid Naskh Shift Alt", 1, 14)); // NOI18N
        pistasExistentesjList.setForeground(new java.awt.Color(0, 0, 102));
        jScrollPane5.setViewportView(pistasExistentesjList);

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        agregarPistaListajButton.setText("Agregar a la Lista");
        agregarPistaListajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPistaListajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(203, 203, 203))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(agregarPistaListajButton)
                .addGap(45, 45, 45)
                .addComponent(jButton6)
                .addGap(117, 117, 117))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarPistaListajButton)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        crearNuevaListajButton.setText("Crear Una Nueva Pista");
        crearNuevaListajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearNuevaListajButtonActionPerformed(evt);
            }
        });

        nombreNuevaListajTextField.setBackground(new java.awt.Color(255, 255, 255));
        nombreNuevaListajTextField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombreNuevaListajTextField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre de la Pista:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreNuevaListajTextField))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(crearNuevaListajButton)
                                        .addGap(0, 24, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(titlepistaModifjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreNuevaListajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(crearNuevaListajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(titlepistaModifjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Edicion Listas-Pistas", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jMenu2.setText("File");

        CrearPistajMenuItem.setText("Crear Pista");
        CrearPistajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPistajMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(CrearPistajMenuItem);

        jMenuItem1.setText("Guardar Pista");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem6.setText("Recuperar del Archivo bin");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");

        jMenuItem2.setText("Errores Lexicos");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Errores Sintacticos");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Errores Semanticos");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");

        jMenuItem5.setText("Repositorio GitHub");
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reproducirListajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproducirListajButtonActionPerformed
        // TODO add your handling code here:
        if (ListaListasjList.getSelectedIndex() != -1) {
            this.listaenReproduccion = this.majeList.mostrarPistasDeLaLista(pistasListaReprojList, ListaListasjList.getSelectedIndex());

        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una lista!!");
        }

    }//GEN-LAST:event_reproducirListajButtonActionPerformed

    private void compilarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compilarjButtonActionPerformed
        // TODO add your handling code here:
        Reader reader = new StringReader(LenguajePistajTextArea.getText());
        this.lexer = new LexerPista(reader);
        this.parser = new parser(lexer);
        FunMensaje.getInstanceMensajes().getMensajes().clear();
        ManejadorPistaMusical.getPistaMusical().getCanales().clear();
        ErroresSingleton.getInstance().clear();
        try {
            parser.parse();
            ErroresSingleton.getInstance().setErroresSemanticos(parser.getErrorsSemanticos());
            this.ConsolaPistasjTextArea1.setText("");
            if (ErroresSingleton.getInstance().existenErrores(LenguajePistajTextArea)) {
                this.textoSalida();
                parser.getPista().setCodigoFuente(this.LenguajePistajTextArea.getText());
                parser.getPista().autoguardar();
                PistasCompiladas.getInstancePistasActivacion().guardarEnBinario();
                this.majeList.mostrarListasJlist(ListaListasjList);
                this.majeList.mostrarPistasExistentes(pistasExistentesjList);
                this.majeList.limpiarJlist(pistasListaReprojList);
                JOptionPane.showMessageDialog(null, "Compilado exitosa, para probar la pista puede ir al area de Biblioteca");
            } else {
                JOptionPane.showMessageDialog(null, "Compilacion no Exitosa, revisar los detalles de los reportes de errores");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Compilacion no Exitosa, revisar los detalles de los reportes de errores");
            ErroresSingleton.getInstance().setErroresSemanticos(parser.getErrorsSemanticos());
            this.ConsolaPistasjTextArea1.setText("Uff! se llego a un error critico en la compilacion: Revisa los reportes de errores, Semanticos, Lexicos y Sintancticos");
            //ex.printStackTrace();
        }
    }//GEN-LAST:event_compilarjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!yoTeDetube) {
            if (pistasListaReprojList.getSelectedIndex() != -1) {
                this.reproducctor = new HiloReproductorDePista();
                this.reproducctor.prepararReproduccion(this.listaenReproduccion.getListasMusicales().get(pistasListaReprojList.getSelectedIndex()).getCanales());
                this.reproducctor.start();
                yoTeDetube = true;
            } else {
                JOptionPane.showMessageDialog(null, "Debes seleccionar una pista para reproducirla");

            }
        } else {
            if (yoTeDetube && !this.reproducctor.getPlayer().getManagedPlayer().isFinished()) {
                yoTeDetube = false;
                this.reproducctor.detenerReproduccion();
            } else {
                if (pistasListaReprojList.getSelectedIndex() != -1) {
                    this.reproducctor = new HiloReproductorDePista();
                    this.reproducctor.prepararReproduccion(this.listaenReproduccion.getListasMusicales().get(pistasListaReprojList.getSelectedIndex()).getCanales());
                    this.reproducctor.start();
                    yoTeDetube = true;
                } else {
                    JOptionPane.showMessageDialog(null, "Debes seleccionar una pista para reproducirla");

                }
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void modificarListajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarListajButtonActionPerformed
        if (this.ListaListasjList.getSelectedIndex() != -1) {
            if (this.ListaListasjList.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Error!, no puede modificar la lista general de pistas");

            } else {
                this.listasEnModificacion = this.majeList.mostrarPistasDeLaLista(modificarListajList, ListaListasjList.getSelectedIndex());
                this.titlepistaModifjLabel.setText(this.listasEnModificacion.getNombre());
                JOptionPane.showMessageDialog(null, "Ok!, dirigete al area de edicion de listas y pistas ya podras editar la lista seleccionada");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una lista!!");
        }
    }//GEN-LAST:event_modificarListajButtonActionPerformed

    private void eliminarListajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarListajButtonActionPerformed
        if (this.ListaListasjList.getSelectedIndex() != -1) {
            if (this.ListaListasjList.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Error!, no puede eliminar la lista general de pistas");
            } else {
                int respuesta = JOptionPane.showConfirmDialog(null, "Seguro de eliminar la Lista?", "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (respuesta == JOptionPane.YES_OPTION) {
                    PistasCompiladas.getInstancePistasActivacion().getListas().remove(this.ListaListasjList.getSelectedIndex());
                    majeList.limpiarJlist(pistasListaReprojList);
                    majeList.limpiarJlist(ListaListasjList);
                    majeList.limpiarJlist(modificarListajList);
                    this.majeList.mostrarListasJlist(ListaListasjList);
                    this.titlepistaModifjLabel.setText("pista a modificar: ------");
                    PistasCompiladas.getInstancePistasActivacion().guardarEnBinario();
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una lista!!");
        }
    }//GEN-LAST:event_eliminarListajButtonActionPerformed

    private void eliminarPistadeListajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPistadeListajButtonActionPerformed
        if (this.modificarListajList.getSelectedIndex() != -1) {
            int respuesta = JOptionPane.showConfirmDialog(null, "Seguro de eliminar la pista?", "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (respuesta == JOptionPane.YES_OPTION) {
                listasEnModificacion.getListasMusicales().remove(this.modificarListajList.getSelectedIndex());
                majeList.limpiarJlist(pistasListaReprojList);
                majeList.limpiarJlist(modificarListajList);
                majeList.mostrarPistasDeLaLista(modificarListajList, listasEnModificacion);
                PistasCompiladas.getInstancePistasActivacion().guardarEnBinario();
                JOptionPane.showMessageDialog(null, "Pista Eliminada Exitosamente de la lista");

            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una Pista!!");

        }


    }//GEN-LAST:event_eliminarPistadeListajButtonActionPerformed

    private void crearNuevaListajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearNuevaListajButtonActionPerformed
        // TODO add your handling code here:
        if (!"".equals(nombreNuevaListajTextField.getText())) {
            PistasCompiladas.getInstancePistasActivacion().guardarNuevaLista(nombreNuevaListajTextField.getText());
            this.titlepistaModifjLabel.setText(nombreNuevaListajTextField.getText());
            majeList.limpiarJlist(ListaListasjList);
            majeList.mostrarListasJlist(ListaListasjList);
            majeList.limpiarJlist(modificarListajList);

        } else {
            JOptionPane.showMessageDialog(null, "Debes ingresar un nombre de la lista!!");
        }
    }//GEN-LAST:event_crearNuevaListajButtonActionPerformed

    private void agregarPistaListajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPistaListajButtonActionPerformed
        // TODO add your handling code here:
        if (this.pistasExistentesjList.getSelectedIndex() != -1) {
            if (titlepistaModifjLabel.getText().equals("Pista En Edicion: -----") || titlepistaModifjLabel.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Selecciona una pista a modificar!");
            } else {
                PistaMusical tmp = PistasCompiladas.getInstancePistasActivacion().getListas().get(0).getListasMusicales().get(this.pistasExistentesjList.getSelectedIndex());
                PistasCompiladas.getInstancePistasActivacion().guardarPistaALista(tmp, titlepistaModifjLabel.getText());
                PistasCompiladas.getInstancePistasActivacion().guardarEnBinario();
                majeList.mostrarPistasDeLaLista(modificarListajList, listasEnModificacion);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una Pista a agregar!");

        }


    }//GEN-LAST:event_agregarPistaListajButtonActionPerformed

    private void CrearPistajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPistajMenuItemActionPerformed
        // TODO add your handling code here:
        if (this.reproducctor.getCombinedPattern() != null && this.reproducctor.getPlayer().getManagedPlayer().isPlaying()) {
            yoTeDetube = false;
            this.reproducctor.detenerReproduccion();
        }
        this.LenguajePistajTextArea.setText("");
    }//GEN-LAST:event_CrearPistajMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "Pista guardada al momento de ser compilada :)");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (this.pistasExistentesjList.getSelectedIndex() != -1) {
            int respuesta = JOptionPane.showConfirmDialog(null, "Seguro de eliminar la pista?", "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (respuesta == JOptionPane.YES_OPTION) {
                int index = this.pistasExistentesjList.getSelectedIndex();
                PistasCompiladas.getInstancePistasActivacion().getListas().get(0).getListasMusicales().remove(index);
                PistasCompiladas.getInstancePistasActivacion().guardarEnBinario();
                this.majeList.mostrarPistasExistentes(pistasExistentesjList);
                JOptionPane.showMessageDialog(null, "Pista elimina con exito!!");

            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona un apista");

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    public void textoSalida() {
        String contenido = FunMensaje.getInstanceMensajes().getContenido();
        this.ConsolaPistasjTextArea1.setText(contenido);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ConsolaPistasjTextArea1;
    private javax.swing.JMenuItem CrearPistajMenuItem;
    private javax.swing.JScrollPane LenguajePistajScrollPane;
    private javax.swing.JTextArea LenguajePistajTextArea;
    private javax.swing.JList<String> ListaListasjList;
    private javax.swing.JPanel PanelEditor;
    private javax.swing.JButton agregarPistaListajButton;
    private javax.swing.JButton compilarjButton;
    private javax.swing.JButton crearNuevaListajButton;
    private javax.swing.JButton eliminarListajButton;
    private javax.swing.JButton eliminarPistadeListajButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton modificarListajButton;
    private javax.swing.JList<String> modificarListajList;
    private javax.swing.JTextField nombreNuevaListajTextField;
    private javax.swing.JList<String> pistasExistentesjList;
    private javax.swing.JList<String> pistasListaReprojList;
    private javax.swing.JButton reproducirListajButton;
    private javax.swing.JLabel titlepistaModifjLabel;
    // End of variables declaration//GEN-END:variables
}
